import sys
sys.path.insert(0, '.')

import time
import uuid

from dotenv import load_dotenv
load_dotenv()


from db import clusters

def seed_clusters():
    clusters.delete_many({})

    sample_clusters = [
        {
            "cluster_id": str(uuid.uuid4()),
            "center": {"type": "Point", "coordinates": [79.9864, 23.1815]},
            "report_count": 28,
            "severity": 0.85,
            "status": "OPEN",
            "priority": 125.4,
            "last_seen": time.time() - 86400,
            "no_detection_count": 0,
            "image_url": None,
            "assigned_to": None,
            "assigned_team": None,
            "location_name": "Wright Town, Near Stadium",
            "city": "Jabalpur",
            "state": "Madhya Pradesh",
            "area_type": "urban",
            "first_seen": time.time() - 12 * 86400,
            "created_at": time.time() - 12 * 86400,
            "unique_vehicle_count": 14,
            "images": [],
            "notes": "Severe damage near high-traffic junction.",
            "internal_notes": ["Contractor notified on April 3", "Material ordered"],
            "deadline": time.time() + 6 * 86400,
            "updated_at": time.time() - 86400,
        },
        {
            "cluster_id": str(uuid.uuid4()),
            "center": {"type": "Point", "coordinates": [79.9335, 23.1685]},
            "report_count": 12,
            "severity": 0.65,
            "status": "IN_PROGRESS",
            "priority": 75.2,
            "last_seen": time.time() - 2 * 86400,
            "no_detection_count": 0,
            "image_url": None,
            "assigned_to": None,
            "assigned_team": "MP-Works-Delta",
            "location_name": "Civic Center Road",
            "city": "Jabalpur",
            "state": "Madhya Pradesh",
            "area_type": "urban",
            "first_seen": time.time() - 10 * 86400,
            "created_at": time.time() - 10 * 86400,
            "unique_vehicle_count": 7,
            "images": [],
            "notes": "",
            "internal_notes": [],
            "deadline": time.time() + 4 * 86400,
            "updated_at": time.time() - 86400,
        },
        {
            "cluster_id": str(uuid.uuid4()),
            "center": {"type": "Point", "coordinates": [72.8777, 19.0760]},
            "report_count": 52,
            "severity": 0.92,
            "status": "OPEN",
            "priority": 148.7,
            "last_seen": time.time() - 3600,
            "no_detection_count": 0,
            "image_url": None,
            "assigned_to": None,
            "assigned_team": None,
            "location_name": "Sion-Panvel Highway",
            "city": "Mumbai",
            "state": "Maharashtra",
            "area_type": "urban",
            "first_seen": time.time() - 9 * 86400,
            "created_at": time.time() - 9 * 86400,
            "unique_vehicle_count": 25,
            "images": [],
            "notes": "",
            "internal_notes": [],
            "deadline": time.time() + 2 * 86400,
            "updated_at": time.time() - 3600,
        },
        {
            "cluster_id": str(uuid.uuid4()),
            "center": {"type": "Point", "coordinates": [72.9781, 19.2183]},
            "report_count": 15,
            "severity": 0.55,
            "status": "RESOLVED",
            "priority": 42.1,
            "last_seen": time.time() - 8 * 86400,
            "no_detection_count": 0,
            "image_url": None,
            "assigned_to": None,
            "assigned_team": "MH-Roads-Bravo",
            "location_name": "Thane Belapur Road",
            "city": "Mumbai",
            "state": "Maharashtra",
            "area_type": "urban",
            "first_seen": time.time() - 20 * 86400,
            "created_at": time.time() - 20 * 86400,
            "unique_vehicle_count": 8,
            "images": [],
            "notes": "Repair completed",
            "internal_notes": ["Repaired on April 10"],
            "deadline": None,
            "updated_at": time.time() - 8 * 86400,
        },
        {
            "cluster_id": str(uuid.uuid4()),
            "center": {"type": "Point", "coordinates": [77.2090, 28.6139]},
            "report_count": 3,
            "severity": 0.30,
            "status": "OPEN",
            "priority": 25.5,
            "last_seen": time.time() - 86400,
            "no_detection_count": 0,
            "image_url": None,
            "assigned_to": None,
            "assigned_team": None,
            "location_name": "Janpath Road, New Delhi",
            "city": "Delhi",
            "state": "Delhi",
            "area_type": "urban",
            "first_seen": time.time() - 4 * 86400,
            "created_at": time.time() - 4 * 86400,
            "unique_vehicle_count": 2,
            "images": [],
            "notes": "",
            "internal_notes": [],
            "deadline": time.time() + 11 * 86400,
            "updated_at": time.time() - 86400,
        },
        {
            "cluster_id": str(uuid.uuid4()),
            "center": {"type": "Point", "coordinates": [77.5946, 12.9716]},
            "report_count": 36,
            "severity": 0.88,
            "status": "IN_PROGRESS",
            "priority": 112.3,
            "last_seen": time.time() - 2 * 3600,
            "no_detection_count": 0,
            "image_url": None,
            "assigned_to": None,
            "assigned_team": "KA-Roads-Sierra",
            "location_name": "Indiranagar 100ft Road",
            "city": "Bengaluru",
            "state": "Karnataka",
            "area_type": "urban",
            "first_seen": time.time() - 12 * 86400,
            "created_at": time.time() - 12 * 86400,
            "unique_vehicle_count": 18,
            "images": [],
            "notes": "",
            "internal_notes": [],
            "deadline": time.time() + 3 * 86400,
            "updated_at": time.time() - 2 * 3600,
        },
        {
            "cluster_id": str(uuid.uuid4()),
            "center": {"type": "Point", "coordinates": [80.0500, 23.2300]},
            "report_count": 20,
            "severity": 0.78,
            "status": "OPEN",
            "priority": 98.5,
            "last_seen": time.time() - 3600 * 8,
            "no_detection_count": 0,
            "image_url": None,
            "assigned_to": None,
            "assigned_team": None,
            "location_name": "Rural Road Sector 4, Panagar",
            "city": "Jabalpur",
            "state": "Madhya Pradesh",
            "area_type": "rural",
            "first_seen": time.time() - 6 * 86400,
            "created_at": time.time() - 6 * 86400,
            "unique_vehicle_count": 12,
            "images": [],
            "notes": "",
            "internal_notes": [],
            "deadline": time.time() + 8 * 86400,
            "updated_at": time.time() - 3600 * 8,
        },
        {
            "cluster_id": str(uuid.uuid4()),
            "center": {"type": "Point", "coordinates": [80.9462, 26.8467]},
            "report_count": 14,
            "severity": 0.62,
            "status": "OPEN",
            "priority": 68.9,
            "last_seen": time.time() - 4 * 3600,
            "no_detection_count": 0,
            "image_url": None,
            "assigned_to": None,
            "assigned_team": None,
            "location_name": "Gomti Nagar Link Road",
            "city": "Lucknow",
            "state": "Uttar Pradesh",
            "area_type": "urban",
            "first_seen": time.time() - 5 * 86400,
            "created_at": time.time() - 5 * 86400,
            "unique_vehicle_count": 9,
            "images": [],
            "notes": "",
            "internal_notes": [],
            "deadline": time.time() + 7 * 86400,
            "updated_at": time.time() - 4 * 3600,
        },
    ]

    result = clusters.insert_many(sample_clusters)
    print(f"Seeded {len(result.inserted_ids)} clusters successfully")

    print(f"Total: {clusters.count_documents({})}")
    print(f"Open: {clusters.count_documents({'status': 'OPEN'})}")
    print(f"In Progress: {clusters.count_documents({'status': 'IN_PROGRESS'})}")
    print(f"Resolved: {clusters.count_documents({'status': 'RESOLVED'})}")
    print(f"High Priority: {clusters.count_documents({'priority': {'$gte': 100}})}")

if __name__ == "__main__":
    seed_clusters()